export enum AppActionTypes  {
    SET_FILMS = 'app/SET_FILMS',
    REORDER_FILMS = 'app/REORDER_FILMS',
    DUPLICATE_FILM = 'app/DUPLICATE_FILM',
    CHANGE_RATE_FILMS = 'app/CHANGE_RATE_FILMS',
    SET_AUTHOR= 'app/SET_AUTHOR'
}